### ISSUE TITLE
Snap: app doesn't load on ubuntu 18.04.1

### ISSUE THREAD

**Issue by DouglasDev** [zulip/zulip-desktop#593]
I installed the app from Ubuntu software center. It doesn't load at all. error message is:
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Failed to generate minidump.Segmentation fault (core dumped)

**Comment by jakobkolb** [comment]
Can confirm this.

**Comment by jakobkolb** [comment]
Apparently, only the Snap available over the Software center is broken. Following the installation instructions from the readme (https://zulipchat.com/help/desktop-app-install-guide) everything worked fine.

**Comment by timabbott** [comment]
@jakobkolb thanks for the report, that's very helpful!  Tagging this as a top priority.

**Comment by akashnimare** [comment]
Thanks for the report, let me see what's wrong.

**Comment by akashnimare** [comment]
@DouglasDev you tried the deb format, right? Just to be clear this is what you have followed -
* Downloaded the deb installer from https://zulipchat.com/apps/linux
* Open the downloaded file in ubuntu software centre + installed it
* Run Zulip and got above error

If yes then can you try installing the deb installer from the terminal using -
```sh
sudo dpkg -i Zulip-2.3.82-amd64.deb
```

I have tried AppImage + deb installer on Ubuntu 16.04 LTS and it works as expected. You can also install Zulip using our snap installer -

https://snapcraft.io/zulip

> Apparently, only the Snap available over the Software center is broken.

@jakobkolb I have pushed v2.3.82 on [snapcraft](https://snapcraft.io/zulip). Can you check if this fixes the issue for you?

**Comment by caemor** [comment]
I just installed zulip via snap (2.3.82) and still get the same error as above on ubuntu 18.04.
`libcanberra-gtk-module` is installed.

**Comment by akashnimare** [comment]
Okay, this works great on Ubuntu 16.04. You might need to install some libraries in order to run it..can you paste the exact error here?

**Comment by caemor** [comment]
It's the same error which DouglasDav posted as the first entry for this issue.

**Comment by caemor** [comment]
Might be related to https://github.com/electron/electron/issues/13767 and other linked issues there :thinking:

**Comment by akashnimare** [comment]
The issue looks related to electron-userland/electron-builder#2981

Could you folks try some of the tips in https://askubuntu.com/questions/342202/failed-to-load-module-canberra-gtk-module-but-already-installed and see if it works?

**Comment by akashnimare** [comment]
>  electron/electron#13767 

No, since we're not using the `powerMonitor` api. The other possible reason could be Sentry.

**Comment by caemor** [comment]
> Could you folks try some of the tips in https://askubuntu.com/questions/342202/failed-to-load-module-canberra-gtk-module-but-already-installed and see if it works?

I already tried all of them but the last one (`sudo apt-get install libcanberra-gtk*`) and they didn't help me.

**Comment by akashnimare** [comment]
Okay, I can reproduce this error now. I'm still trying to figure out what's wrong with the snap. This works as expected if I build it locally and install it but doesn't work if I download this from the snap store.

**Comment by akashnimare** [comment]
Similar issues -
https://github.com/burtonator/polar-bookshelf/issues/257
https://forum.snapcraft.io/t/apparmor-error-with-org-freedesktop-login1-manager/8164/8

**Comment by popey** [comment]
@akashnimare left a comment on your [forum thread](https://forum.snapcraft.io/t/snap-fails-to-load-error-minidump-segmentation-fault/8691/4?u=popey).

**Comment by vsvipul** [comment]
had the same issue.. can confirm this :+1:

**Comment by akashnimare** [comment]
@popey I actually don’t know if that `yaml` file is being used or not. Can you help me out on this i.e. what should I check/debug in order to get rid of the error?

**Comment by One111** [comment]
Same issue.
Ubuntu 18.04.1 LTS

`Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Failed to generate minidump.Segmentation fault (core dumped)`

**Comment by ghost** [comment]
i solved temporally my problem using the Appimage version. I did:

1. Download: [chmod a+x Zulip-x.x.x-x86_64.AppImage](https://zulipchat.com/apps/linux)
2. Change permissions: 
`sudo chmod a+x Zulip-x.x.x-x86_64.AppImage`
3. Rename: 
`sudo mv Zulip-2.3.82-x86_64.AppImage zulip`
4. And copy to /usr/bin: 
`sudo cp zulip  /usr/bin/`

So, just execute on terminal and work for me!

**Comment by krkolek** [comment]
I tried install zulip following the instructions from https://zulipchat.com/help/desktop-app-install-guide and I test all ways to do it:
- apt - works and I can pin app to the favourites
- AppImage - works
- snap - I have the same error as in the first post.

**Comment by akashnimare** [comment]
Just pushed a new beta for Snap. Can you folks test it out?
https://snapcraft.io/zulip

**Comment by vsvipul** [comment]
@akashnimare All functionality is working fine now. Great to know that the segfault has fixed. It will be great if others test it out too. @caemor  @isasouza-com  @kanishk98 .
You need to test the beta using
```
sudo snap install zulip --beta
```

**Comment by akashnimare** [comment]
This issue has been fixed in the latest beta. Feel free to re-open if this occurs again.

**Comment by abhigyank** [comment]
Any pointers on what change fixed it?

**Comment by akashnimare** [comment]
I think a combination of - updating electron-builder + https://github.com/zulip/zulip-electron/commit/8a0b047d8f28d55b547e0af14969e3559d86eb92 fixed this issue.
